### ISSUE TITLE
Leaked MongoDB Password / Server

### ISSUE THREAD

**Issue by TimWeidner** [cleverCoader/mern-tinder-clone#1]
Hey @cleverCoader,
We noticed your MongoDB ConnectionString was pushed to github. This is pretty bad practice and thus we decided we'd have a little fun with your test images. Since you are pretty new on github I'd advice you not to push critical data to your repositories since everybody can use them (as you have seen).

For this project I'd adivce you to do at least the following:
- changing your mongodb password
- create a json file with your credentials
- a .gitignore file with that file listed
- remove the old connection string and load the new one from your created json file.

After doing that, you are not pushing your credentials to github, so only you can access your database afterwards.

Best regards,
Tim

**Comment by cleverCoader** [comment]
What the hell I am pretty new to GitHub but I was very afraid that someone
hacked it and changed images my bad , I finally received this mail from you
and I was somewhat ok now , yeah thanks for the hat advice 🙏🙏

**Comment by TimWeidner** [comment]
Sorry if I scared you. Was just supposed to be some harmless fun. I didn't mean to cause any offense.
